# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75085b5ecacc747df3fd2b48dda7399e0c122dde3d19b1e2f58ddf95a72910a606ae8d9fd0c25ec2a079799ed63c66777510750cc4a76064108137475f357a66

test:
  secret_key_base: a937b49f6469db26bd8cd56ef45975766d606093562677603ef03ed3b64ca4f297527fe1a90ce398457f7762d0b82f660d30a511c27c0ad9a5c822f3971ee07e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
